Translate: Ubuntu Server: Virtualization
ubuntu-kr/blog pull request #52
Opened 2022-05-26 14:33 UTC by GiyeonBang

1. qemu ~ libvirt #14
2. virtmanager ~ swtpm #15

2022-05-26 17:28 UTC, sukso96100 commented
base branch를 jammy-release-note 로 바꿔주세요

2022-05-26 17:34 UTC, GiyeonBang commented
> base branch를 jammy-release-note 로 바꿔주세요

앗, 실수했군요. 곧바로 수정했습니다.

2022-05-28 08:37 UTC, sukso96100 requested changes
수고 많으셨습니다. 몇가지만 커멘트 체크 하셔서 개선 해 주시면 되겠습니다 :)

2022-05-28 08:37 UTC, sukso96100 commented on content/post/jamme-jellyfish-release-notes/index.md
> + * microvm build를 위한 기타 장치 (`virtio-gpu`, `vhost-user-gpu`, `virtio-input-host`, `vhost_user_input`)
```suggestion
 * microvm build를 위한 더 많은 장치 (`virtio-gpu`, `vhost-user-gpu`, `virtio-input-host`, `vhost_user_input`)
```

2022-05-28 08:37 UTC, sukso96100 commented on content/post/jamme-jellyfish-release-notes/index.md
> + * 추가 드라이버 `qemu-block-extra`의 제거를 허용합니다.
```suggestion
 * `qemu-block-extra`의 추가 드라이버 제거를 허용합니다.
```

2022-05-28 08:37 UTC, sukso96100 commented on content/post/jamme-jellyfish-release-notes/index.md
> + * 많은 추가 개선 사항에 대한 개요는 버전 [6.1](https://wiki.qemu.org/ChangeLog/6.1) 및 [6.2](https://wiki.qemu.org/ChangeLog/6.2)에 대한 업스트림 변경 기록을 참조하십시오. 여기에는 제거되거나, 추천하지 않거나, 호환되지 않는 기능에 대한 제한된 대안 목록도 포함됩니다.
```suggestion
 * 더 많은 추가 개선 사항에 대한 개요는 버전 [6.1](https://wiki.qemu.org/ChangeLog/6.1) 및 [6.2](https://wiki.qemu.org/ChangeLog/6.2)에 대한 업스트림 변경 기록을 참조하십시오. 여기에는 제거되거나, 추천하지 않거나, 호환되지 않는 기능에 대한 제한된 대안 목록도 포함됩니다.
```

2022-05-28 08:37 UTC, sukso96100 commented on content/post/jamme-jellyfish-release-notes/index.md
>   * qemu: Add new API to inject a launch secret in a domain
여기 번역 해 주세요

2022-05-31 02:22 UTC, GiyeonBang commented
네, 내일 중으로 작업하겠습니다.

2022-06-01 10:52 UTC, GiyeonBang commented
1. 제안해주신 번역을 모두 수락했습니다.
2. 빠진 부분을 번역했습니다.

2022-06-01 11:38 UTC, sukso96100 approved these changes
수고 많으셨습니다 :)

2022-06-01 11:38 UTC, merged